platform :ios, '9.0'

target 'FlexLayout-OC_Example' do
  pod 'FlexLayout-OC', :path => '../'
  pod 'ZZFLEX', :git => 'https://github.com/tbl00c/ZZFLEX.git'
  pod 'GMYogaKit'

  target 'FlexLayout-OC_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'  # required
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
